project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Linear Regression in R"
  chapters:
   - index.qmd
   - Regression.qmd
   - OLS_example.qmd
   
format: html
engine: knitr



