project:
  type: book
  output-dir: docs
engine: knitr

book:
  title: Introduction to Linear Regression in R
  chapters:
  - index.qmd
  - LinearModels.qmd
  - Fitting.qmd
  - Diagnostics.qmd
  - MultipleLinearRegression.qmd
format:
  live-html:
    toc: true
    number-depth: 2
css: include/webex.css
include-after-body: include/webex.js
