project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Linear Regression in R"
  chapters:
   - index.qmd
   - LinearModels.qmd
   - Fitting.qmd
   - Diagnostics.qmd
   - MultipleLinearRegression.qmd
   
format: html
engine: knitr



