---
title: "OldCh1webx"
format: html
---


:::: {.webex-check .webex-box}
#### Your turn

A second company also has a job available. The *starting salary* is
higher here - \$70,000 on average - but payrises are smaller. You are
told that, on average, employees working for the company for 5 years
earn \$20,000 more per year than when they started.

You want to use a simple linear prediction to calculate your expected
salary ($E[Y]$) after $X$ years of employment.

$$
E[Y] = \beta_0 + \beta_1 X
$$

1.  What are the coefficients $\beta_0$ and $beta_1$ in this case?

```{r}
#| echo: false
#| results: 'asis'
library(webexercises)
beta0_quiz <- fitb(answer= 70000, num=TRUE)
beta1_quiz <- fitb(answer=4000, num=TRUE)
```

$\beta_0 =$`{r} I(beta0_quiz)` $\beta_1 =$`{r} I(beta1_quiz)`

Using R, calculate the expected salary after working for this company
for 10 years

```{webr}
#| exercise: example_2

```

```{webr}
#| exercise: example_2
#| check: true
if (identical(.result, 70000+(4000*10))) {
  list(correct = TRUE, message = "Nice work!")
} else {
  list(correct = FALSE, message = "That's incorrect, sorry.")
}
```

2.  Complete the r function that predicts $Y$ from an input $X$ for this
    linear model (alternatively - give function e.g. 'this function
    predicts salary at company 2 with an input X years work')

```{webr}
#| exercise: r_function
#| envir: linear_predictor_function
linear_prediction <- function(X){__ + (__*__)}
```

```{webr}
#| exercise: example_2
#| check: true
if (identical(.result, 50000+(5000*10))) {
  list(correct = TRUE, message = "Nice work!")
} else {
  list(correct = FALSE, message = "That's incorrect, sorry.")
}
```

Use this function to predict $Y$ for the following values of $X$

```{webr}
#| edit: false
X <- c(9,4,5,2,6)
```

```{webr}
#| exercise: r_function_call
#| envir: linear_predictor_function


```

```{webr}
#| exercise: r_function_call
#| check: true
if (identical(.result, 50000+(5000*X))) {
  list(correct = TRUE, message = "Nice work!")
} else {
  list(correct = FALSE, message = "That's incorrect, sorry.")
}
```

::: ToDo
add plot comparing two (companies) linear salary growth?
:::